WITH maf_trades AS (
    SELECT
        F.OTCTRANDIMID,
        F.DTPROCESS,
        TS.STRADESTATUS,
        DS.SDATASOURCENAME,
        DK.SDESK,
        RPT.SRISKINSTRUMENTTYPE,
        CO.COUNTRYDIMID AS MATCHED_COUNTRYDIMID
    FROM TABLE($OtcTranFact) F
    INNER JOIN TABLE($OtcTranDim) D
        ON D.OTCTRANDIMID = F.OTCTRANDIMID
    INNER JOIN TABLE($Entity) EN
        ON EN.ENTITYDIMID = F.ENTITYDIMID
    LEFT JOIN TABLE($TradeStatus) TS
        ON TS.TRADESTATUSDIMID = F.TRADESTATUSDIMID
    LEFT JOIN TABLE($DataSource) DS
        ON DS.DATASOURCEDIMID = F.DATASOURCEDIMID
    LEFT JOIN TABLE($Account) TA
        ON TA.ACCOUNTDIMID = D.TRADINGACCOUNTDIMID
    LEFT JOIN TABLE($TradeBook) TB
        ON TB.TRADEBOOKDIMID = TA.TRADEBOOKDIMID
    LEFT JOIN TABLE($Desk) DK
        ON DK.DESKDIMID = TB.DESKDIMID
    LEFT JOIN TABLE($Account) CPTY
        ON CPTY.ACCOUNTDIMID = D.CPTYACCOUNTDIMID
    LEFT JOIN TABLE($ParentAccount) PA
        ON PA.PARENTACCOUNTDIMID = CPTY.PARENTACCOUNTDIMID
    LEFT JOIN TABLE($MasterAccount) MA
        ON MA.MASTERACCOUNTDIMID = PA.MASTERACCOUNTDIMID
    LEFT JOIN TABLE($LegalEntity) LE
        ON LE.LEGALENTITYDIMID = MA.LEGALENTITYDIMID
    LEFT JOIN TABLE($Country) CO
        ON CO.COUNTRYDIMID = LE.RISKCOUNTRYDIMID
    LEFT JOIN TABLE($RiskProductType) RPT
        ON RPT.RISKPRODUCTTYPEDIMID = D.RISKPRODUCTTYPEDIMID
    WHERE EN.SENTITYCODE = 'MAF'
      AND F.PROCESSDATEDIMID BETWEEN $P_dtProcessStart AND $P_dtProcessEnd
),
branches AS (
    SELECT 'Q1_EQD_LEG' AS BRANCH, B.*, P.DTPAYEVENT AS EVENT_DATE,
           P.PAYTYPEDIMID, P.PAYCURRENCYDIMID AS FX_FROM_CURRENCYDIMID
    FROM maf_trades B
    LEFT JOIN TABLE($OtceqdPayScheduleLeg) P ON P.OTCTRANDIMID = B.OTCTRANDIMID

    UNION ALL
    SELECT 'Q2_OTC_PAY', B.*, P.DTPAY,
           P.PAYTYPEDIMID, P.PAYAMOUNTCURRENCYDIMID
    FROM maf_trades B
    LEFT JOIN TABLE($OtcPaySchedule) P ON P.OTCTRANDIMID = B.OTCTRANDIMID

    UNION ALL
    SELECT 'Q3_IRD_LEG', B.*, P.DTPAY,
           P.PAYTYPEDIMID, P.PAYCURRENCYDIMID
    FROM maf_trades B
    LEFT JOIN TABLE($OtcirdPayScheduleLeg) P ON P.OTCTRANDIMID = B.OTCTRANDIMID

    UNION ALL
    SELECT 'Q4_FXD_PAY', B.*, P.DTPAYEVENT,
           P.PAYTYPEDIMID, P.PAYAMOUNTCURRENCYDIMID
    FROM maf_trades B
    LEFT JOIN TABLE($OtcFxdPaySchedule) P ON P.OTCTRANDIMID = B.OTCTRANDIMID

    UNION ALL
    SELECT 'Q5_FX_BUY', B.*, X.DTDELIVERY,
           P.PAYTYPEDIMID, X.BUYCURRENCYDIMID
    FROM maf_trades B
    LEFT JOIN TABLE($OtcPaySchedule) P ON P.OTCTRANDIMID = B.OTCTRANDIMID
    LEFT JOIN TABLE($OtcFxdTran) X ON X.OTCTRANDIMID = B.OTCTRANDIMID

    UNION ALL
    SELECT 'Q6_FX_SELL', B.*, X.DTDELIVERY,
           P.PAYTYPEDIMID, X.SELLCURRENCYDIMID
    FROM maf_trades B
    LEFT JOIN TABLE($OtcPaySchedule) P ON P.OTCTRANDIMID = B.OTCTRANDIMID
    LEFT JOIN TABLE($OtcFxdTran) X ON X.OTCTRANDIMID = B.OTCTRANDIMID
),
joined AS (
    SELECT
        B.*,
        PT.SPAYTYPENAME,
        EXC.EXCHANGERATETYPEDIMID AS MATCHED_RATE_TYPE_DIMID
    FROM branches B
    LEFT JOIN TABLE($PayType) PT
        ON PT.PAYTYPEDIMID = B.PAYTYPEDIMID
    LEFT JOIN TABLE($ExchangeRate) EXC
        ON EXC.DTEXCHANGERATE = B.DTPROCESS
       AND EXC.FROMCURRENCYDIMID = B.FX_FROM_CURRENCYDIMID
       AND EXC.EXCHANGERATETYPEDIMID IN (
           SELECT EXCHANGERATETYPEDIMID
           FROM TABLE($ExchangeRatetype)
           WHERE SEXCHANGERATETYPECODE = 'DISC'
       )
       AND EXC.TOCURRENCYDIMID IN (
           SELECT CURRENCYDIMID
           FROM TABLE($Currency)
           WHERE SCURRENCYCODEISO = 'USD'
       )
),
flags AS (
    SELECT
        BRANCH,
        OTCTRANDIMID,
        IFF(MATCHED_COUNTRYDIMID IS NOT NULL, 1, 0) AS COUNTRY_OK,
        IFF(MATCHED_RATE_TYPE_DIMID IS NOT NULL, 1, 0) AS RATE_OK,
        IFF(STRADESTATUS = 'ACTIVE', 1, 0) AS STATUS_OK,
        -- The first four branches apply this filter; FX-buy and FX-sell
        -- branches have it commented out in the attached draft.
        -- Verify the exact INCREMENTAL INTEREST literal in working SQL.
        IFF(BRANCH IN ('Q5_FX_BUY', 'Q6_FX_SELL') OR
            (UPPER(SPAYTYPENAME) <> 'INCREMENTAL INTEREST' OR SPAYTYPENAME IS NULL), 1, 0) AS PAYTYPE_OK,
        IFF(UPPER(SDATASOURCENAME) = 'MUREX', 1, 0) AS SOURCE_OK,
        IFF(UPPER(SDESK) NOT IN ('TECHNICAL BOOK','TECH PORTFOLIOS'), 1, 0) AS DESK_OK,
        IFF(EVENT_DATE > TRY_TO_DATE($P_dtProcessStart::VARCHAR, 'YYYYMMDD'), 1, 0) AS EVENT_DATE_OK,
        -- Intentional SQL 3-valued logic: NULL here becomes NOT PASS.
        IFF(NOT (UPPER(SRISKINSTRUMENTTYPE) IN
             ('SWAPTION BERMUDAN','SWAPTION EUROPEAN','STRADDLE SWAPTION')
             AND UPPER(SPAYTYPENAME) = 'COUPON'), 1, 0) AS SWAPTION_OK,
        IFF(UPPER(SRISKINSTRUMENTTYPE) <> 'DEPO'
            AND UPPER(SRISKINSTRUMENTTYPE) <> 'INTERAFFILIATE LOAN'
            AND UPPER(SRISKINSTRUMENTTYPE) <> 'SUBORDINATED DEBT', 1, 0) AS FINAL_RISK_OK
    FROM joined
)
SELECT
    BRANCH,
    COUNT(*) AS MAF_JOINED_CANDIDATE_ROWS,
    SUM(IFF(COUNTRY_OK=1, 1, 0)) AS AFTER_COUNTRY,
    SUM(IFF(COUNTRY_OK=1 AND RATE_OK=1, 1, 0)) AS AFTER_RATE,
    SUM(IFF(COUNTRY_OK=1 AND RATE_OK=1 AND STATUS_OK=1, 1, 0)) AS AFTER_ACTIVE,
    SUM(IFF(COUNTRY_OK=1 AND RATE_OK=1 AND STATUS_OK=1 AND PAYTYPE_OK=1, 1, 0)) AS AFTER_PAYTYPE,
    SUM(IFF(COUNTRY_OK=1 AND RATE_OK=1 AND STATUS_OK=1 AND PAYTYPE_OK=1
            AND SOURCE_OK=1, 1, 0)) AS AFTER_MUREX,
    SUM(IFF(COUNTRY_OK=1 AND RATE_OK=1 AND STATUS_OK=1 AND PAYTYPE_OK=1
            AND SOURCE_OK=1 AND DESK_OK=1, 1, 0)) AS AFTER_DESK,
    SUM(IFF(COUNTRY_OK=1 AND RATE_OK=1 AND STATUS_OK=1 AND PAYTYPE_OK=1
            AND SOURCE_OK=1 AND DESK_OK=1 AND EVENT_DATE_OK=1, 1, 0)) AS AFTER_FUTURE_EVENT,
    SUM(IFF(COUNTRY_OK=1 AND RATE_OK=1 AND STATUS_OK=1 AND PAYTYPE_OK=1
            AND SOURCE_OK=1 AND DESK_OK=1 AND EVENT_DATE_OK=1
            AND SWAPTION_OK=1, 1, 0)) AS AFTER_SWAPTION_RULE,
    SUM(IFF(COUNTRY_OK=1 AND RATE_OK=1 AND STATUS_OK=1 AND PAYTYPE_OK=1
            AND SOURCE_OK=1 AND DESK_OK=1 AND EVENT_DATE_OK=1
            AND SWAPTION_OK=1 AND FINAL_RISK_OK=1, 1, 0)) AS EXPECTED_FINAL_MAF_ROWS
FROM flags
GROUP BY BRANCH
ORDER BY BRANCH;
