WITH maf_base AS (
    SELECT
        F.OTCTRANDIMID,
        F.PROCESSDATEDIMID,
        F.DTPROCESS,
        TS.STRADESTATUS,
        DS.SDATASOURCENAME,
        DK.SDESK,
        CO.COUNTRYDIMID AS MATCHED_COUNTRYDIMID
    FROM TABLE($OtcTranFact) F
    INNER JOIN TABLE($OtcTranDim) D
        ON D.OTCTRANDIMID = F.OTCTRANDIMID
    INNER JOIN TABLE($Entity) EN
        ON F.ENTITYDIMID = EN.ENTITYDIMID
    LEFT JOIN TABLE($TradeStatus) TS
        ON TS.TRADESTATUSDIMID = F.TRADESTATUSDIMID
    LEFT JOIN TABLE($DataSource) DS
        ON DS.DATASOURCEDIMID = F.DATASOURCEDIMID
    LEFT JOIN TABLE($Account) TA
        ON TA.ACCOUNTDIMID = D.TRADINGACCOUNTDIMID
    LEFT JOIN TABLE($TradeBook) TB
        ON TB.TRADEBOOKDIMID = TA.TRADEBOOKDIMID
    LEFT JOIN TABLE($Desk) DK
        ON DK.DESKDIMID = TB.DESKDIMID
    LEFT JOIN TABLE($Account) CPTY
        ON CPTY.ACCOUNTDIMID = D.CPTYACCOUNTDIMID
    LEFT JOIN TABLE($ParentAccount) PA
        ON PA.PARENTACCOUNTDIMID = CPTY.PARENTACCOUNTDIMID
    LEFT JOIN TABLE($MasterAccount) MA
        ON MA.MASTERACCOUNTDIMID = PA.MASTERACCOUNTDIMID
    LEFT JOIN TABLE($LegalEntity) LE
        ON LE.LEGALENTITYDIMID = MA.LEGALENTITYDIMID
    LEFT JOIN TABLE($Country) CO
        ON CO.COUNTRYDIMID = LE.RISKCOUNTRYDIMID
    WHERE EN.SENTITYCODE = 'MAF'
)
SELECT
    COUNT(*) AS MAF_BASE_ROWS,
    SUM(IFF(PROCESSDATEDIMID BETWEEN $P_dtProcessStart AND $P_dtProcessEnd, 1, 0)) AS PASS_PROCESS_DATE,
    SUM(IFF(PROCESSDATEDIMID BETWEEN $P_dtProcessStart AND $P_dtProcessEnd
             AND STRADESTATUS = 'ACTIVE', 1, 0)) AS PASS_DATE_AND_STATUS,
    SUM(IFF(PROCESSDATEDIMID BETWEEN $P_dtProcessStart AND $P_dtProcessEnd
             AND STRADESTATUS = 'ACTIVE'
             AND UPPER(SDATASOURCENAME) = 'MUREX', 1, 0)) AS PASS_PLUS_MUREX,
    SUM(IFF(PROCESSDATEDIMID BETWEEN $P_dtProcessStart AND $P_dtProcessEnd
             AND STRADESTATUS = 'ACTIVE'
             AND UPPER(SDATASOURCENAME) = 'MUREX'
             AND UPPER(SDESK) NOT IN ('TECHNICAL BOOK','TECH PORTFOLIOS'), 1, 0)) AS PASS_PLUS_DESK,
    SUM(IFF(PROCESSDATEDIMID BETWEEN $P_dtProcessStart AND $P_dtProcessEnd
             AND STRADESTATUS = 'ACTIVE'
             AND UPPER(SDATASOURCENAME) = 'MUREX'
             AND UPPER(SDESK) NOT IN ('TECHNICAL BOOK','TECH PORTFOLIOS')
             AND MATCHED_COUNTRYDIMID IS NOT NULL, 1, 0)) AS PASS_PLUS_COUNTRY
FROM maf_base;
